SOME BASIC NPM COMMANDS

NPN 
NPN -- VERSION
NODE --VERSION
PYTHON --VERSION
NPM INIT
NPM INSTALL EXPESS
NPM INSTALL SLUGIFY
NPM UNINSTALL EXPRESS
NPM INSTALL NODEMON --SAVE-DEV
NPM INSTALL NODEMON --GLOBAL